### ISSUE TITLE
Unexpected Token

### ISSUE THREAD

**Issue by mgtelford** [probil/vue-product-carousel#1]
I am receiving a compiling error with the carousel.vue file.
Here is my component:
```
<template>
  <carousel :images="media"></carousel>
</template>
<script>
export default {
    data: function () {
        return {
            test: true
        }
    },
    props: {
      media: {
          type: Array,
          required: true
      }
    },
    replace: true,
    computed: {},
    methods: {},
    components: {
      carousel: require('vue-product-carousel')
    }
}
</script>
```
Has anyone else had the same compiling message?

> Browserify failed!: Unexpected token  node_modules/vue-product-carousel/src/carousel.vue:1
<template>
^

**Comment by probil** [comment]
Hi, @mgtelford. Are you using `babel` with `browserify`? `node_modules` can be ignored, so you should exclude the lib from ignoring. Soon, I will provide new version of lib with no need for ES6 compilation

**Comment by mgtelford** [comment]
Right now we are using laravel-elixir-vueify

**Comment by probil** [comment]
I have updated lib to the `0.2.0` version. Now it should work well with `browserify` and `webpack` without any issue (`babel` no more required).
Waiting for your feedback

**Comment by mgtelford** [comment]
@probil 
It worked. I appreciate your help.

**Comment by probil** [comment]
@mgtelford It's seems like issue can be closed
