### ISSUE TITLE
Images aren't working on Netlify

### ISSUE THREAD

**Issue by guastallaigor** [probil/vue-product-carousel#59]
Just to let you know, your cloudinary images on [Netlify](https://vue-product-carousel.netlify.com/) (demo) are not working at the moment. They all return 404.

**Comment by probil** [comment]
Oh, I've borrowed them somewhere on the internet. Need to upload them to the reliable place.
Thanks @guastallaigor for reporting will try to fix today

**Comment by probil** [comment]
Fixed, hope you'll like new images :)
